#Experiment config
moving_avg_window_size: 1
base_path: "/home/magraz/morphology-learning/experiments/results"

# batches: ["multi_box_push_test"]
# batches: ["smacv2_5m_vs_6m"]
# batches: ["rendezvouz_12a"]
# batches: ["scatter_12a"]
# batches: ["contact_12a"]
# batches: ["multi_box_push_9a_3o", "hrl_skill_agent_9a", "hrl_skill_team_9a"]
# batches: ["dcg_smaclite_2s3z"]
# batches: ["smaclite_3s_vs_5z"]
# batches: ["macro_mjx_16a_4o","mjx_16a_4o", "macro_mjx_16a_4o_dr", "macro_mjx_16a_4o_wdr", "macro_mjx_16a_4o_stagger", "macro_mjx_16a_4o_stagger_wdr", "macro_mjx_16a_4o_stagger_wdr_aligned"]
# batches: ["mjx_6a_4o_1024_gs"]
batches: ["mjx_1a_3o_111_1024_gs"]
# batches: ["mjx_2a_4o_1122_1024"]

# batches: ["smax_10m_vs_11m"]


# experiments: ["gcn", "gat", "graph_transformer", "gcn_full", "gat_full", "graph_transformer_full"]
# experiments: ["hygma", "hgnn_shared", "learned_affinity", "mlp_shared"]
# experiments: ["mlp", "feudal_film", "feudal_film_n001", "feudal_film_n001_dilated", "feudal_film_zerogoal", "feudal_film_n01", "feudal_film_n05", "feudal_film_zerogoal_dilated", "feudal_film_n01_dilated", "feudal_film_n05_dilated"]
# experiments: ["mlp","feudal_film_local", "feudal_film_n01_local", "feudal_film_n05_local", "feudal_film_n001_local", "feudal_film_n01", "feudal_film_n05", "feudal_film_n001"]
# experiments: ["mlp","feudal_film_local", "feudal_film_n01_local"]
experiments: ["mlp", "feudal_film_zerogoal", "feudal_intrinsic", "feudal_intrinsic_local_private", 
"feudal_n01", "feudal_n05", "feudal_film_n01_direction", "feudal_film_n01_waypoint",
"feudal_n01_c50", "feudal_n05_c50"]

# "feudal_n01", "feudal_n01_local_private", "feudal_n01_local_shared",
# "feudal_n05", "feudal_n05_local_private", "feudal_n05_local_shared", "feudal_n05_local_private_shared",
# "feudal_film_direction", "feudal_film_waypoint", 
# "feudal_film_n01_waypoint", "feudal_film_n01_direction",
# "feudal_n01_c50", "feudal_n01_local_private_c50",
# "feudal_n05_c50", "feudal_n05_local_private_c50" ]

# experiments: ["mlp", "feudal_n05_local_shared", "feudal_n05_local_private_shared", "feudal_n01_local_shared", "feudal_film_direction", "feudal_film_waypoint", "feudal_film_n01_waypoint"]

# experiments: ["mlp","feudal_film_local_global", "feudal_film_n01_local_global", "feudal_film_n05_local_global", "feudal_film_n001_local_global"]


custom_labels:
  hgnn_shared: Typed Hypergraph Critic + MAPPO
  hgnn_proximity: Typed Hypergraph Critic + MAPPO

plot_colors:
  hgnn_mix: "tab:purple"
  multi_box_push_12a_6o_dense/mlp_shared: "tab:red"


# trials: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"]
trials: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"]
# trials: ["0", "1", "2"]
