#Experiment config
moving_avg_window_size: 1
datapoints: [50000, 30000]
base_path: "/home/magraz/morphology-learning/experiments/results"

# batches: ["multi_box_push_test"]
# batches: ["smacv2_5m_vs_6m"]
batches: ["smaclite_2s3z_test"]

# experiments: ["gcn", "gat", "graph_transformer", "gcn_full", "gat_full", "graph_transformer_full"]
experiments: ["mlp_shared"]

# trials: ["0", "1", "2", "3", "4"]

trials: ["test"]

